spring:
  application:
    name: tracker-tkd
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
